# Generated by Django 5.0.1 on 2026-02-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodscan',
            name='meal_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
